#!/usr/bin/env bash

# USAGE IS: $ env - $(add-to-env /path/to/your/file)

# This is necessary because running $ env - $(env; /path/to/your/file) does not work when there is an
# environment variable that has spaces in it (THANKS WHOEVER DID THAT)

env_files="$@"


# SET THESE TO NULL FOR THE TIME BEING BECAUSE THEY FUCK EVERYTHING UP WITH THEIR SPACES
SSH_CONNECTION=
LESSCLOSE=
LESSOPEN=
SSH_CLIENT=

env
cat $env_files
