#!/usr/bin/env python3
import subprocess
import os
import argparse

def get_arguments():
    parser = argparse.ArgumentParser()
    bools = parser.add_argument_group()

    parser.add_argument('domain_names', help='Any full domains that you want to get a tls certificate for; separated by commas (example: timetrack.slgotting.com,staging.timetrack.slgotting.com')

    parser.add_argument('project_name', help="The name of the project, or the repository's name", default="temp")

    parser.add_argument('-u', '--username', type=str, required=True,
                        help='The user calling this script. Since this is run as sudo it is necessary')

    parser.add_argument('-e', '--email_address', type=str, required=True,
                        help='The email address to point LetsEncrypt to, so we can run the script non-interactively')

    bools.add_argument('-t', '--testing', action='store_true',
                       help='If ticked, we will use the staging environment for letsencrypt and certbot')

    args = parser.parse_args()

    return args

SERVER_CODE = lambda domains: f'''
server {{
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    server_name {' '.join(domains.split(','))};
}}
'''

def main(args):

    username = args.username

    subprocess.run('sudo apt update', shell=True)
    subprocess.run('sudo apt install -y certbot', shell=True)
    subprocess.run('sudo apt install -y python3-certbot-nginx', shell=True)

    with open(f'/etc/nginx/conf.d/{args.project_name}.conf', 'w+') as f:
        f.write(SERVER_CODE(args.domain_names))

    subprocess.run('sudo nginx -t && sudo nginx -s reload', shell=True)

    if os.path.exists("/etc/nginx/conf.d/default.conf"):
        os.remove("/etc/nginx/conf.d/default.conf")
    if os.path.exists("/etc/nginx/sites-enabled/default"):
        os.remove("/etc/nginx/sites-enabled/default")

    test = "--test-cert" if args.testing else ''
    domains_string = " ".join(f"-d {domain}" for domain in args.domain_names.split(','))
    subprocess.run(f'sudo certbot --nginx --non-interactive --agree-tos {test} --email {args.email_address} {domains_string}', shell=True)

    line="0 12 * * * /usr/bin/certbot renew --quiet"
    subprocess.run(f'(crontab -u {username} -l; echo "{line}" ) | crontab -u {username} -', shell=True)


if __name__ == '__main__':
    args = get_arguments()
    print(args)
    main(args)
