#!/usr/bin/env python3

import argparse


def get_arguments():
    parser = argparse.ArgumentParser()

    # argument groups can have their tickers combined (ie -su)
    bools = parser.add_argument_group()

    # REQUIRED string value
    parser.add_argument(
        'username', help="The url of video or playlist desired")

    # integer value
    parser.add_argument('-m', '--max', default=136, type=int,
                        help="")

    # boolean (default=False; store_true means if ticked then args['ugly'] == True)
    bools.add_argument('-u', dest="ugly", action="store_true",
                       help="are you ugly")

    # boolean (default=True; store_false means if ticked then args['sexy'] == False)
    bools.add_argument('-s', dest="sexy", action="store_false",
                       help="are you sexy")

    args = parser.parse_args()

    return args


args = get_arguments()
print(args)
