#!/usr/bin/env python3
import subprocess
import os
import argparse

def get_arguments():
    parser = argparse.ArgumentParser()

    # argument groups can have their tickers combined (ie -su)
    bools = parser.add_argument_group()
    
    

    args = parser.parse_args()

    return args


if __name__ == '__main__':
    cmd = '''sudo apt-add-repository ppa:ansible/ansible
    sudo apt update
    sudo apt install ansible'''


    subprocess.run(cmd.strip().replace('\n', '&&').replace('\t', '')
, shell=True)


