#!/usr/bin/env python3
import subprocess
import os
import argparse
import time


def get_arguments():
    parser = argparse.ArgumentParser()

    # argument groups can have their tickers combined (ie -su)
    bools = parser.add_argument_group()

    parser.add_argument('-u', '--username', default='steven',
                        help='The username to be created (default: steven)')

    parser.add_argument('-r', '--remote_ip',
                        help='Remote IP of the machine were connecting to.')

    bools.add_argument('-d', '--docker', action='store_true',
                       help='should we install docker?')
    bools.add_argument('-c', '--compose', action='store_true',
                       help='should we install docker-compose?')
    bools.add_argument('-n', '--node', action='store_true',
                       help='should we install node?')

    args = parser.parse_args()

    return args


def verify_location(location):
    input(
        f"This step is meant to be executed on the {location}. Press enter to continue (verify) or Ctrl-C if you're in the wrong location")


if __name__ == '__main__':

    args = get_arguments()
    print(args)

    verify_location('Local machine')
    remote_ip = args.remote_ip if args.remote_ip else input(
        'What is the IP of the remote host? ')

    setup_command = f"""
        adduser {args.username} &&
        usermod -aG sudo {args.username} &&
        mkdir /home/{args.username}/.ssh
    """.replace('\t', '').replace('\n', '')

    # run initial setup commands
    subprocess.run(f'ssh root@{remote_ip} "{setup_command}"', shell=True)

    # copy ssh key to remote machine
    subprocess.run(
        f"cat ~/.ssh/id_rsa.pub | ssh root@{remote_ip} 'cat >> /home/{args.username}/.ssh/authorized_keys'",
        shell=True)
    subprocess.run(
        f"cat ~/.ssh/id_rsa_do | ssh root@{remote_ip} 'cat > /home/{args.username}/.ssh/id_rsa'",
        shell=True)

    # remove root login access
    subprocess.run(
        f'''ssh root@{remote_ip} "sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config"''',
        shell=True)

    time.sleep(1)
    password = input('Enter sudo password for user setup: ')
    time.sleep(1)
    user_commands = f'''
        echo {password} | sudo -S apt update &&
        echo {password} | sudo -S apt-get install -y python3-pip &&
        pip3 install slg-dev-ops &&
        echo {password} | sudo -S chown -R {args.username} ~/.ssh/ &&
        echo {password} | sudo -S chmod 700 ~/.ssh/ &&
        echo {password} | sudo -S chmod 600 ~/.ssh/*
    '''.replace('\t', '').replace('\n', '')
    subprocess.run(
        f'ssh {args.username}@{remote_ip} "{user_commands}"', shell=True)

    if args.docker:
        cmd = f'''echo {password} | sudo -S apt install -y docker.io &&
                systemctl start docker &&
                systemctl enable docker
                '''
        subprocess.run(
            f'ssh {args.username}@{remote_ip} "{cmd}"', shell=True)
    if args.compose:
        cmd = f'''
            echo {password} | sudo -S curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
            echo {password} | sudo -S chmod +x /usr/local/bin/docker-compose
        '''
        subprocess.run(
            f'ssh {args.username}@{remote_ip} "{cmd}"', shell=True)
        print('Docker compose successfully installed')

    if args.node:
        cmd = f'''
            echo {password} | sudo -S curl -sL https://deb.nodesource.com/setup_16.x -o /home/{args.username}/nodesource_setup.sh &&
            echo {password} | sudo -S bash nodesource_setup.sh &&
            echo {password} | sudo -S apt-get install -y nodejs
        '''
        subprocess.run(
            f'ssh {args.username}@{remote_ip} "{cmd}"', shell=True)
        print('Node/npm successfully installed')

    print(
        f"\n\nNow you can login as {args.username}: ssh {args.username}@{remote_ip}!")

    if args.docker:
        print("\n\nTo start docker run systemctl start docker && systemctl enable docker")

    # # copy github private ssh key from local machine to /Users/{args.username}/.ssh/ directory
    # print(
    #     f'Copying github private ssh key from local machine to /Users/{args.username}/.ssh/ directory')

    # # install homebrew ( for gh installation )
    # print('Installing homebrew')

    # # install gh (brew install gh)
    # print('Installing gh')

    # # clone repo

    # # run docker compose

    # setup nginx proxy?
